version: '3'
services:
  api:
    build: ./api
    user: "node"
    ports:
      - '4000:4000'
    environment:
      NODE_ENV: 'development'
    volumes:
      - ./api:/usr/src/app
    command: npm run start:dev

  app:
    build: ./app
    user: node
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: 'development'
    volumes:
      - ./app:/usr/src/app
    command: npm start